http:
  middlewares:
    opa-authz:
      forwardAuth:
        address: "http://policy.agent:9292/"

  routers:
    ping-api:
      rule: "PathPrefix(`/ping`)"
      tls: {}
      entryPoints:
      - "https"
      - "http"
      service: ping-api-svc
      priority: 50

    data-api:
      rule: "PathPrefix(`/`)"
      tls: {}
      entryPoints:
      - "https"
      - "http"
      service: data-api-svc
      priority: 30
      middlewares:
      - "default-https"
      - "opa-authz"

    audit-api:
      rule: "PathPrefix(`/_audit`)"
      tls: {}
      entryPoints:
      - "https"
      - "http"
      service: audit-api-svc
      priority: 35
      middlewares:
      - "default-https"
      - "opa-authz"

    search-api:
      rule: "PathPrefix(`/_search`)"
      tls: {}
      entryPoints:
      - "https"
      - "http"
      service: search-api-svc
      priority: 35
      middlewares:
      - "default-https"
      - "opa-authz"

    browse-api:
      rule: "PathPrefix(`/_browse`)"
      tls: {}
      entryPoints:
      - "https"
      - "http"
      service: browse-api-svc
      priority: 35
      middlewares:
      - "default-https"
      - "opa-authz"

    codetabel-api:
      rule: "PathPrefix(`/_codetable`)"
      tls: {}
      entryPoints:
        - "https"
        - "http"
      service: codetabel-api-svc
      priority: 35
      middlewares:
        - "default-https"
        - "opa-authz"

    data-logic-api:
      rule: "PathPrefix(`/_logic`)"
      tls: {}
      entryPoints:
      - "https"
      - "http"
      service: data-logic-api-svc
      priority: 35
      middlewares:
      - "default-https"
      - "opa-authz"

    audit-logic-api:
      rule: "PathPrefix(`/_audit/_logic`)"
      tls: {}
      entryPoints:
        - "https"
        - "http"
      service: audit-logic-api-svc
      priority: 34
      middlewares:
        - "default-https"
        - "opa-authz"

    policy-agent:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - "opa"
      service: policy-agent-svc

  services:
    ping-api-svc:
      loadBalancer:
        servers:
        - url: http://ping.api:9292

    data-api-svc:
      loadBalancer:
        servers:
        - url: http://data.api:9292

    audit-api-svc:
      loadBalancer:
        servers:
        - url: http://audit.api:9292

    search-api-svc:
      loadBalancer:
        servers:
        - url: http://search.api:9292

    browse-api-svc:
      loadBalancer:
        servers:
        - url: http://browse.api:9292

    codetabel-api-svc:
      loadBalancer:
        servers:
          - url: http://codetabel.api:9292

    data-logic-api-svc:
      loadBalancer:
        servers:
        - url: http://data_logic.api:9292

    audit-logic-api-svc:
      loadBalancer:
        servers:
          - url: http://audit_logic.api:9292

    policy-agent-svc:
      loadBalancer:
        servers:
          - url: http://opa:8181