tcp:
  routers:
    kafka:
      rule: "HostSNI(`*`)"
      entryPoints: 
      - "kafka"
      service: kafka-svc
      
  services:
    kafka-svc:
      loadBalancer:
         servers:
           - address: "kafka:9092"
