version: '3.8'
networks:
  public:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/16
    driver_opts:
      com.docker.network.bridge.name: docker_public

  private:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
    driver_opts:
      com.docker.network.bridge.name: docker_private
      com.docker.network.bridge.enable_icc: 1
      com.docker.network.bridge.enable_ip_masquerade: 1

services:
  traefik:
    image: traefik:2.8.3
    restart: unless-stopped
    container_name: traefik
    command:
      - --configFile=/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/traefik/conf:/traefik
      - ./volumes/traefik/logs:/logs
    networks:
      - public
      - private

  virtuoso:
    image: registry.docker.libis.be/library/virtuoso:7.2.5
    restart: unless-stopped
    hostname: virtuoso
    container_name: virtuoso
    mem_limit: 8g
    mem_reservation: 3g
    environment:
      SPARQL_UPDATE: 'true'
      DEFAULT_GRAPH: https://data.archiefpunt.be/
    volumes:
      - "./volumes/virtuoso/data/db:/data"
    networks:
      - private

  elastic:
    image: elasticsearch:8.4.1
    container_name: elastic
    restart: unless-stopped
    mem_limit: 4g
    mem_reservation: 750m
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      discovery.type: single-node
      xpack.security.enabled: 'false'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - private
    volumes:
      - "./volumes/elastic/data:/usr/share/elasticsearch/data"
      - "./volumes/elastic/logs:/usr/share/elasticsearch/logs"

  kibana:
    image: kibana:8.4.1
    container_name: kibana
    networks:
      - private
    links:
      - elastic:elasticsearch
    depends_on:
      - elastic

  data-api:
    image: registry.docker.libis.be/archiefpunt/data
    restart: unless-stopped
    environment:
      SERVICE_ROLE: data
    deploy:
      replicas: 3
    hostname: data.api
    volumes:
      - "./volumes/api/config:/app/config"
      - "./volumes/api/data:/app/data"
      - "./volumes/api/cache:/app/cache"
    networks:
      - private
    links:
      - virtuoso:virtuoso

  audit-api:
    image: registry.docker.libis.be/archiefpunt/data
    restart: unless-stopped
    container_name: audit.api
    hostname: audit.api
    environment:
      SERVICE_ROLE: audit
    volumes:
      - "./volumes/api/config:/app/config"
      - "./volumes/api/cache:/app/cache"
    networks:
      - private
    links:
      - virtuoso:virtuoso

  search-api:
    image: registry.docker.libis.be/archiefpunt/search
    restart: unless-stopped
    hostname: search.api
    deploy:
      replicas: 2
    environment:
      SERVICE_ROLE: search
    volumes:
      - "./volumes/api/config:/app/config"
      - "./volumes/api/cache:/app/cache"
    networks:
      - private
    links:
      - elastic:elastic

  browse-api:
    image: registry.docker.libis.be/archiefpunt/search
    restart: unless-stopped
    hostname: browse.api
    deploy:
      replicas: 2
    environment:
      SERVICE_ROLE: browse
    volumes:
      - "./volumes/api/config:/app/config"
      - "./volumes/api/cache:/app/cache"
    networks:
      - private
    links:
      - elastic:elastic

  codetabel-api:
    image: registry.docker.libis.be/archiefpunt/search
    restart: unless-stopped
    hostname: codetabel.api
    deploy:
      replicas: 2
    environment:
      SERVICE_ROLE: codetable
    volumes:
      - "./volumes/api/config:/app/config"
      - "./volumes/api/cache:/app/cache"
    networks:
      - private
    links:
      - elastic:elastic

  data-logic-api:
    image: registry.docker.libis.be/archiefpunt/logic
    restart: unless-stopped
    container_name: data_logic.api
    hostname: data_logic.api
    environment:
      SERVICE_ROLE: data_logic
    volumes:
      - "./volumes/api/config:/app/config"
      - "./volumes/api/cache:/app/cache"
    networks:
      - private
    links:
      - virtuoso:virtuoso

  audit-logic-api:
    image: registry.docker.libis.be/archiefpunt/logic
    restart: unless-stopped
    container_name: audit_logic.api
    hostname: audit_logic.api
    environment:
      SERVICE_ROLE: audit_logic
    volumes:
      - "./volumes/api/config:/app/config"
      - "./volumes/api/cache:/app/cache"
    networks:
      - private
    links:
      - virtuoso:virtuoso

  ping-api:
    image: registry.docker.libis.be/archiefpunt/ping
    restart: unless-stopped
    container_name: ping.api
    hostname: ping.api
    environment:
      SERVICE_ROLE: ping
    volumes:
      - "./volumes/api/config:/app/config"
      - "./volumes/api/cache:/app/cache"
    networks:
      - private

  event-listener:
    image: registry.docker.libis.be/archiefpunt/loaders
    restart: unless-stopped
    container_name: listener.event
    hostname: listener.event
    tty: true
    environment:
      SERVICE_ROLE: listener
    volumes:
      - "./volumes/api/config:/app/config"
      - "./volumes/api/data:/app/data"
      - "./volumes/api/cache:/app/cache"
    networks:
      - private
    links:
      - elastic:elastic
      - audit-api:audit-api

  policy-agent:
    image: registry.docker.libis.be/archiefpunt/policy-agent
    restart: unless-stopped
    container_name: policy.agent
    hostname: policy.agent
    depends_on:
      - opa
    environment:
      SERVICE_ROLE: policy_agent
    volumes:
      - "./volumes/api/config:/app/config"
      - "./volumes/api/cache:/app/cache"
    networks:
      - private

  opa:
    image: openpolicyagent/opa:latest-debug
#    image: openpolicyagent/opa:latest-rootless
    restart: unless-stopped
    networks:
      - private
    volumes:
      - ./volumes/opa/policies:/policies
    depends_on:
      - opa-bundle-server
    environment:
      SECRET: $JWT_SECRET
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--bundle"
      - "--watch"
      - "--log-format=json-pretty"
      - "--log-level=debug"
      - "--set=decision_logs.console=true"
      - "--set=services.nginx.url=http://opa-bundle-server"
      - "--set=bundles.nginx.service=nginx"
      - "--set=bundles.nginx.resource=archiefpunt.tar.gz"
      - "--set=bundles.nginx.polling.min_delay_seconds=10"
      - "--set=bundles.nginx.polling.max_delay_seconds=30"

  opa-bundle-server:
    image: nginx
    restart: unless-stopped
    networks:
      - private
    volumes:
      - ./volumes/opa/bundled_policies:/usr/share/nginx/html

