---
:key: AIzaSyAMCvXqkGUAr5QE-ERg6n94ug5JbcKi_qU
:debug: true

:services:
  :data:
    :host: "http://127.0.0.1:9292"
    :base_path: "/"
  :search:
    :host: "http://127.0.0.1:9494"
    :base_path: "/_search"
    :rules: "./config/search_rules.rb"
    :elastic:
      :mapping: "./config/elastic.json"
      :host: "http://127.0.0.1:9201"
      :index: "archiefpunt"
      :templates:
        :query: config/search_elastic/query.json
        :mapping:
          :sort: config/search_elastic/mappings/sort_mapping.json
          :facet: config/search_elastic/mappings/facet_mapping.json
          :index: config/search_elastic/mappings/index_mapping.json
          :query_string: config/search_elastic/mappings/query_string.json
          :query_mapping: config/search_elastic/mappings/query_mapping.json
  :browse:
    :host: "http://127.0.0.1:9595"
    :base_path: "/_browse"
    :rules: "./config/browse_rules.rb"
    :elastic:
      :mapping: "./config/elastic.json"
      :host: "http://127.0.0.1:9201"
      :index: "archiefpunt"
      :templates:
        :query: config/browse_elastic/query.json
        :mapping:
          :sort: config/browse_elastic/mappings/sort_mapping.json
          :facet: config/browse_elastic/mappings/facet_mapping.json
          :index: config/browse_elastic/mappings/index_mapping.json
          :query_string: config/browse_elastic/mappings/query_string.json
          :query_mapping: config/browse_elastic/mappings/query_mapping.json
  :audit:
    :host: "http://127.0.0.1:9393"
    :base_path: "/_audit"
  :logic:
    :host: "http://127.0.0.1:9393"
    :base_path: "/_logic"
    :logics: ./config/logics


:solis:
  :cache: ./cache
  :cache_expire: 86400
  :graph_name: https://abv.libis.be/
  :graph_prefix: abv
  :sparql_endpoint: http://127.0.0.1:8892/sparql
  :inflections: ./config/solis/abv.json
  :language: nl

:shape: ./config/solis/abv_shacl.ttl
:cache: ./cache
:cache_expire: 86400
:sheets:
  :abv: 1xhvOCfiSIOtHjIJUtRrxvJ54OoDosNJ_JsA1B7FfpsI
  :audit: 1uaQmU9gcCCRI57VKNEobT5pZvBoSGAyeGApdypspX_g
:redis:
  url: "redis://127.0.0.1:6379/3"
  queue: 'archiefpunt'
:kafka:
  name: 'archiefpunt'
  config:
    :bootstrap.servers: 127.0.0.1:9092
