---
:secret: OPA_SECRET
:key: YOUR_GOOGLE_API_KEY
:debug: true

:solis_data: &SOLIS_DATA
  :cache: ./cache
  :cache_expire: 86400
  :graph_name: https://data.q.archiefpunt.be/
  :graph_prefix: abv
  :sparql_endpoint: http://virtuoso:8890/sparql
  :inflections: ./config/solis/abv.json
  :language: nl
  :shape: ./config/solis/abv_shacl.ttl
  :hooks: ./config/data_hooks.rb

:solis_audit: &SOLIS_AUDIT
  :cache: ./cache
  :graph_name: https://data.q.archiefpunt.be/_audit/
  :graph_prefix: audit
  :sparql_endpoint: http://virtuoso:8890/sparql
  :inflections: ./config/solis/audit.json
  :language: nl
  :shape: ./config/solis/audit_shacl.ttl

:services:
  :ping:
    :host: "http://ping.api:9292"
    :base_path: "/ping"
  :data:
    :host: "http://data.api:9292"
    :base_path: "/"
    :ping_path: ""
    :solis: *SOLIS_DATA
  :search:
    :host: "http://search.api:9292"
    :base_path: "/_search"
    :ping_path: "/ping"
    :rules: "./config/elastic/search/search_rules.rb"
    :elastic:
      :mapping: "./config/elastic/elastic.json"
      :host: "http://elastic:9200"
      :index: "archiefpunt"
      :templates:
        :date_range_relation: INTERSECTS
        :query: config/elastic/search/query.json
        :mapping:
          :sort: config/elastic/search/mappings/sort_mapping.json
          :facet: config/elastic/search/mappings/facet_mapping.json
          :index: config/elastic/search/mappings/index_mapping.json
          :query_string: config/elastic/search/mappings/query_string.json
          :query_mapping: config/elastic/search/mappings/query_mapping.json
  :browse:
    :host: "http://browse.api:9292"
    :base_path: "/_browse"
    :ping_path: "/ping"
    :rules: "./config/elastic/browse/browse_rules.rb"
    :elastic:
      :mapping: "./config/elastic/elastic.json"
      :host: "http://elastic:9200"
      :index: "archiefpunt"
      :templates:
        :date_range_relation: INTERSECTS
        :query: config/elastic/browse/query.json
        :mapping:
          :sort: config/elastic/browse/mappings/sort_mapping.json
          :facet: config/elastic/browse/mappings/facet_mapping.json
          :index: config/elastic/browse/mappings/index_mapping.json
          :query_string: config/elastic/browse/mappings/query_string.json
          :query_mapping: config/elastic/browse/mappings/query_mapping.json
  :audit:
    :host: "http://audit.api:9292"
    :base_path: "/_audit"
    :ping_path: ""
    :solis: *SOLIS_AUDIT
  :logic:
    :host: "http://logic.api:9292"
    :base_path: "/_logic"
    :ping_path: "/ping"
    :logics: ./config/logics
    :solis: *SOLIS_DATA
  :audit_logic:
    :host: "http://audit_logic.api:9292"
    :base_path: "/_audit/_logic"
    :ping_path: "/ping"
    :logics: ./config/audit
    :solis: *SOLIS_AUDIT
  :codetable:
    :host: "http://codetabel.api:9292"
    :base_path: "/_codetable"
    :ping_path: "/ping"
    :rules: "./config/elastic/codetable/codetable_rules.rb"
    :elastic:
      :mapping: "./config/elastic/elastic.json"
      :host: "http://elastic:9200"
      :index: "archiefpunt_codetables"
      :templates:
        :date_range_relation: INTERSECTS
        :query: config/elastic/codetable/query.json
        :mapping:
          :sort: config/elastic/codetable/mappings/sort_mapping.json
          :facet: config/elastic/codetable/mappings/facet_mapping.json
          :index: config/elastic/codetable/mappings/index_mapping.json
          :query_string: config/elastic/codetable/mappings/query_string.json
          :query_mapping: config/elastic/codetable/mappings/query_mapping.json
          :pipeline: config/elastic/search/mappings/pipeline.json          
  :policy_agent:
    :host: "http://policy.agent:9292"
    :base_path: "/"
    :ping_path: "/ping"
    :opa:
      :url: http://opa:8181/v1/data
      :policy: /archiefpunt/authz/allow


:events: /app/data
:cache: ./cache
:cache_expire: 86400
:sheets:
  :abv: 1xhvOCfiSIOtHjIJUtRrxvJ54OoDosNJ_JsA1B7FfpsI
  :audit: 1uaQmU9gcCCRI57VKNEobT5pZvBoSGAyeGApdypspX_g