PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX abv: <https://data.q.archiefpunt.be/>

construct {
    ?agent_id a abv:Agent ;
        abv:archiefbestand ?bronverwijzing_archief ;
        abv:archiefbankrecord ?bronverwijzing_record .
} where {
    {{VALUES}}
    #    VALUES ?archief_id { <https://data.archiefpunt.be/archieven/1007-A944-E024-9196-98AE13348AE9>}
    #VALUES ?agent_id { <https://data.archiefpunt.be/agenten/ABDA-E68D-0AF3-9960-1F11534BW9A4> }
    ?agent_id abv:id ?id;
        abv:identificatienummer ?identificatienummer_id ;
        abv:identificatienummer/abv:id ?id_identificatienummer_id ;
        abv:identificatienummer/abv:waarde ?identificatienummer_waarde .

    ?agent_id rdf:type ?entity_type.

    ?agent_id abv:naam ?agent_naam_id .
    ?agent_naam_id abv:waarde ?agent_naam .
    optional {
        ?agent_naam_id abv:type/abv:label "voorkeursnaam"@nl .
    }

    optional {
        ?agent_id         abv:datering_text ?datering .
    }

    optional {
        ?agent_id         abv:datering_systematisch ?datering_systematisch .
    }

    optional {
        ?identificatienummer_id abv:identificatienummer/abv:type/abv:label "persistente URI"@nl
    }
    bind (CONCAT(STR(DAY(NOW())), "/", STR(MONTH(NOW())), "/", STR(YEAR(NOW()))) as ?displayDate) .

    bind(lcase(replace(str(?entity_type), "https://data.archiefpunt.be/", "")) as ?short_entity_type).

    bind(year(strdt(coalesce(strbefore(?datering_systematisch, '/'), '0001'),xsd:dateTime )) as ?start_datering)
    bind(year(strdt(coalesce(strafter(?datering_systematisch, '/'), '9999') ,xsd:dateTime )) as ?eind_datering)
    bind(concat(str(?start_datering),'-', str(?eind_datering)) as ?een_datering)

    bind(concat(str(?agent_naam),
                   ": ",
                   ?een_datering,
                   "</br>",
                   "<a href='{{LINK}}'>{{LINK}}</a>" )
        as ?bronverwijzing_archief
    ) .

    #"<a href='/", ?short_entity_type, "/", ?id, "'>", ?identificatienummer_waarde, "</a>" )
    bind(concat("Archiefpunt: ", ?agent_naam, '. ', str(?een_datering)," In: <a href='{{LINK}}'>{{LINK}}</a>",
                   "</br>", "(Geraadpleegd op ",?displayDate,")" )
        as ?bronverwijzing_record
    ) .
}