PREFIX abv: <https://data.archiefpunt.be/>

CONSTRUCT {
    ?samensteller_id a abv:Samensteller ;
        abv:id ?id;
        abv:record_type "samensteller";
        abv:agent ?agent_id ;
        abv:functie_beroep_activiteit ?functie ;
        abv:archief_titel ?archief_titel_id .

    ?agent_id a abv:Agent ;
                abv:identificatienummer ?agent_identificatienummer_id ;
                abv:naam ?agent_naam_id;
                abv:type ?agent_type;
                abv:datering_systematisch ?agent_datering_systematisch ;
                abv:datering_text ?agent_datering_text ;
                abv:geschiedenis_agent ?agent_geschiedenis_agent ;
                abv:taal ?agent_taal ;
                abv:associaties ?agent_associaties ;
                abv:bronnen_agent ?agent_bronnen_agent ;
                abv:bibliografie_agent ?agent_bibliografie_agent ;
                abv:bronverwijzing_record ?agent_bronverwijzing_record;
                abv:opmerking ?agent_opmerking .

    ?agent_identificatienummer_id a abv:Identificatie;
                                   abv:bron ?agent_identificatienummer_bron_id;
                                   abv:type ?agent_identificatienummer_type;
                                   abv:waarde ?agent_identificatienummer_waarde.

   ?agent_naam_id a abv:Naam;
       abv:waarde ?agent_naam_waarde;
       abv:type ?agent_naam_type.
}
WHERE {
    {{VALUES}}

    ?samensteller_id a abv:Samensteller ;
        abv:id ?id;
        abv:agent ?agent_id .

    OPTIONAL {
        ?samensteller_id abv:functie_beroep_activiteit/abv:label ?functie .
    }
    # ####### AGENT
    #identificatienummer

    ?agent_id abv:identificatienummer ?agent_identificatienummer_id .

    optional {
        ?agent_identificatienummer_id abv:waarde ?agent_identificatienummer_waarde .
    }
    optional {
        ?agent_identificatienummer_id abv:type/abv:label ?agent_identificatienummer_type .
    }
    optional {
        ?agent_identificatienummer_id abv:bron ?agent_identificatienummer_bron_id .
    }

    #naam
    ?agent_id abv:naam ?agent_naam_id ;
        abv:type/abv:label ?agent_type .

    optional {
        ?agent_id abv:bronverwijzing_record ?agent_bronverwijzing_record .
    }

    ?agent_naam_id abv:waarde ?agent_naam_waarde .
    ?agent_naam_id abv:type_naam/abv:label ?agent_naam_type .

    optional {
        ?agent_id abv:datering_text ?agent_datering_text .
    }
    optional {
        ?agent_id abv:datering_systematisch ?agent_datering_systematisch .
    }

    optional {
        ?agent_id abv:geschiedenis_agent ?agent_geschiedenis_agent .
    }
    optional {
        ?agent_id abv:taal/abv:label ?agent_taal .
    }
    optional {
        ?agent_id abv:associaties ?agent_associaties .
        optional {
            ?agent_associaties abv:plaats/abv:plaatsnaam ?agent_associatie_plaats .
        }
        optional {
            ?agent_associaties abv:agent ?agent_associatie_agent .
        }
        optional {
            ?agent_associaties abv:periode/abv:label ?agent_associatie_periode .
        }
        optional {
            ?agent_associaties abv:onderwerp/abv:label ?agent_associcatie_onderwerp .
        }
    }
    optional {
        ?agent_id abv:bronnen_agent ?agent_bronnen_agent .
    }
    optional {
        ?agent_id abv:bibliografie_agent ?agent_bibliografie_agent .
    }
    optional {
        ?agent_id abv:opmerking ?agent_opmerking .
    }

    bind (CONCAT(STR(YEAR(NOW())), "-", STR(MONTH(NOW())), "-", STR(DAY(NOW()))) as ?generatedDate) .
}