PREFIX abv: <https://data.q.archiefpunt.be/>

construct {
    ?agent_id a abv:UiBewaarplaatsLijst;
        abv:naam ?agent_naam;
        abv:az ?agent_naam_az.
} where {
    ?s abv:agent/abv:naam/abv:waarde ?agent_naam;
        abv:agent/abv:naam ?agent_id ;
        a abv:Beheerder.
    bind(lcase(substr(replace(?agent_naam, '[^a-zA-Z]+',''),1,1)) as ?agent_naam_az) .
}
